services:

  kafka:
    image: apache/kafka-native:4.3.1
    ports:
      - "9092:9092"

  producer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: telemetry-producer
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      - kafka

  consumer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: telemetry-consumer
    env_file:
      - .env
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      AWS_ACCESS_KEY_ID: ${KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${SECRET_KEY}
      AWS_REGION: ${AWS_REGION}
      S3_BUCKET_NAME: ${S3_BUCKET_NAME}
    depends_on:
      - kafka

  spark-silver:
    image: apache/spark:4.0.1-python3
    container_name: telemetry-spark-silver
    environment:
      AWS_ACCESS_KEY_ID: ${KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${SECRET_KEY}
      AWS_REGION: ${AWS_REGION}
      S3_BUCKET_NAME: ${S3_BUCKET_NAME}
    volumes:
      - ./spark:/app
    working_dir: /app
    command: >
      /opt/spark/bin/spark-submit
      --conf spark.jars.ivy=/tmp/.ivy2
      --packages org.apache.hadoop\:hadoop-aws:3.4.1,com.amazonaws\:aws-java-sdk-bundle:1.12.780
      /app/silver_stream.py

  spark-gold:
    image: apache/spark:4.0.1-python3
    container_name: telemetry-spark-gold
    environment:
      AWS_ACCESS_KEY_ID: ${KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${SECRET_KEY}
      AWS_REGION: ${AWS_REGION}
      S3_BUCKET_NAME: ${S3_BUCKET_NAME}
    volumes:
      - ./spark:/app
    working_dir: /app
    command: >
      /opt/spark/bin/spark-submit
      --conf spark.jars.ivy=/tmp/.ivy2
      --packages org.apache.hadoop\:hadoop-aws:3.4.1,com.amazonaws\:aws-java-sdk-bundle:1.12.780
      /app/gold_stream.py